//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCPolandAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCPolandAPI.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHOR NOT FOUND.
        /// </summary>
        public static string authorNotFound {
            get {
                return ResourceManager.GetString("authorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author creating....
        /// </summary>
        public static string creatingAuthor {
            get {
                return ResourceManager.GetString("creatingAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author deleting....
        /// </summary>
        public static string deletingAuthor {
            get {
                return ResourceManager.GetString("deletingAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all authors....
        /// </summary>
        public static string gettingAllAuthors {
            get {
                return ResourceManager.GetString("gettingAllAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting author....
        /// </summary>
        public static string gettingAuthor {
            get {
                return ResourceManager.GetString("gettingAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEM NOT FOUND.
        /// </summary>
        public static string itemNotFound {
            get {
                return ResourceManager.GetString("itemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation succeeded.
        /// </summary>
        public static string succeeded {
            get {
                return ResourceManager.GetString("succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNEXPECTED ERROR OCCURED.
        /// </summary>
        public static string unexpectedError {
            get {
                return ResourceManager.GetString("unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author updating....
        /// </summary>
        public static string updatingAuthor {
            get {
                return ResourceManager.GetString("updatingAuthor", resourceCulture);
            }
        }
    }
}
